### ISSUE TITLE
Lets see if I can send some PR's 

### ISSUE THREAD

**Issue by tcsiwula** [o1-labs/snarky#1]
Please create some issues that you need help with!

**Comment by nicola** [comment]
Awesome work with this library, it would be awesome to get some documentation starting! :)

**Comment by bkase** [comment]
I recently worked on the tutorial so I made some issues around that: #22, #23, and #24 . I'll talk to @imeckler next week and we'll try to come up with tasks in the core lib for contributors to work on too.
