### ISSUE TITLE
Support export / import from R1CS json format

### ISSUE THREAD

**Issue by amiller** [o1-labs/snarky#2]
I don't have a handy reference to point to for this standard format... I'll try to update this issue when I find one

**Comment by imeckler** [comment]
Thanks! That would be great

**Comment by barryWhiteHat** [comment]
@amiller  https://github.com/barryWhiteHat/libsnark-tutorial/blob/master/zksnark_element/r1cs.json

Also if you export proving key , verification key like https://github.com/barryWhiteHat/libsnark-tutorial/tree/master/zksnark_element you can use https://github.com/barryWhiteHat/snarkWrapper to add ethereum auto deployment.

**Comment by nicola** [comment]
Also relevant: https://github.com/JacobEberhardt/ZoKrates/issues/19
