### ISSUE TITLE
snarky circuit for pairing computation

### ISSUE THREAD

**Issue by amakerofbonnetsandhoods** [o1-labs/snarky#231]
Hi all,

Is there any snarky code that do pairing computation? Or did anyone implement a circuit for pairings or more generally for proof verification? 

Thanks,

**Comment by mrmr1993** [comment]
Hi @amakerofbonnetsandhoods, sounds like you might be interested in Snarkette in our Coda repo [here](https://github.com/CodaProtocol/coda/tree/master/src/lib/snarkette).

**Comment by amakerofbonnetsandhoods** [comment]
Hi @mrmr1993  does Snarkette generates a verifier circuit using MNT4 or MNT6 curve?

**Comment by mrmr1993** [comment]
The verifier is modular over the curve, so you can choose which to use. There's a `Groth_maller` submodule in each of the curve modules (`Mnt4_80`, `Mnt4753`, `Mnt6_80`, `Mnt673`) containing the matching verifier circuit.

**Comment by amakerofbonnetsandhoods** [comment]
There isn't any client as in Zokrates or snarkjs where one can compile into R1CS, generate a proof... ? Or maybe an example of using recursive snarks with snarky?
Thanks,

**Comment by mrmr1993** [comment]
For generating proofs, you can create a proof system from a checked computation with [`Proof_system.create`](https://o1-labs.github.io/snarky/api/snarky/Snarky/Snark_intf/module-type-S/Proof_system/index.html#val-create), then generate proofs using [`Proof_system.prove`](https://o1-labs.github.io/snarky/api/snarky/Snarky/Snark_intf/module-type-S/Proof_system/index.html#val-prove) and verify them with [`Proof_system.verify`](https://o1-labs.github.io/snarky/api/snarky/Snarky/Snark_intf/module-type-S/Proof_system/index.html#val-verify). The [tutorial](https://github.com/o1-labs/snarky/blob/master/examples/tutorial/tutorial.ml) uses an older version of the API to generate proofs, but is generally a good place to start.

At present, the only real examples of using snarkette are in the coda code itself.

**Comment by imeckler** [comment]
@amakerofbonnetsandhoods There is actually: it's in the coda repo. 

- The pairing is [here](https://github.com/CodaProtocol/coda/tree/master/src/lib/snarky_pairing)
- Verifiers that make use of the pairing are [here](https://github.com/CodaProtocol/coda/tree/master/src/lib/snarky_verifier)

Note that these use the "old-style" monadic API for snarky.

**Comment by amakerofbonnetsandhoods** [comment]
@imeckler Thanks! and how would you use these snarky monadic API to generate a verifier circuit given a proof and a set of verification keys?
