### ISSUE TITLE
 Unbound value solution?

### ISSUE THREAD

**Issue by njlr** [o1-labs/snarky#281]
Quite often I get this error when trying to generate keys:

```
Error: Unbound value solution.
```

 * What does this mean?
 * How can I fix it?

**Comment by mrmr1993** [comment]
The  `unbound value` means that the compiler can't find a definition for that name before that reference. Here, it probably means that some code refers to `solution`, but it's not defined anywhere.

I normally hit this when I make a typo in the definition name, I would check there first.

**Comment by njlr** [comment]
Ah, so I was missing a `let` in front of the definition of `solution`. 

Perhaps the error message should be: 

```
Error: Unbound value "solution"
```

Here the quotes indicate that the value that is unbound was provided by the user. 

Thanks for your help!

**Comment by njlr** [comment]
(or perhaps I could choose better variable names!)
