### ISSUE TITLE
How to get Balance for a specific testnet transaction ?

### ISSUE THREAD

**Issue by bcashier** [o1-labs/snarky#302]
Hi

Is there a way to get balance of a specific transaction please ?

Thank you

**Comment by mrmr1993** [comment]
Hi @bcashier, the best place to get answers about the coda testnet and the implementation in general is the [coda discord channel](https://discord.gg/vFJjgU4). You can also raise issues with coda on the issue tracker [here](https://github.com/CodaProtocol/coda/issues).

**Comment by bcashier** [comment]
Thank you
