### ISSUE TITLE
snarky does not exist in docker hub

### ISSUE THREAD

**Issue by deepakraous** [o1-labs/snarky#31]
I tried searching for snarky on [docker hub](https://hub.docker.com/) not able find the [repo](https://github.com/o1-labs/snarky
), 

**https://hub.docker.com/search/?isAutomated=0&isOfficial=0&page=1&pullCount=0&q=snarky&starCount=0**

I believe this is needed to install snarky from docker when you install using "docker build -t snarky ."

**Comment by jkrauska** [comment]
@deepakraous adding it shortly -- thanks!
