### ISSUE TITLE
"Hello Prove Me" -Snarky

### ISSUE THREAD

**Issue by deepakraous** [o1-labs/snarky#33]
A simple Hello World like documentation and Code sample needs to be added in the examples. Jumping into a complex example can come later.

**Comment by bkase** [comment]
We had a nice internal discussion about this, thanks for bringing it up! For now look at the tutorial (that holds our simplest examples), but we agree even that needs to be more clear and start with something more like a "hello world." We were thinking about an example of proving you know some preimage to a particular hash i.e. if `y = H(x)`, prove that you know `x` in zero knowledge to some party that only knows `H` and `y`.

**Comment by deepakraous** [comment]
Makes sense, will check out the simpler examples, I do like the example provided for an initial "hello world".
