### ISSUE TITLE
Tutorial Example not working

### ISSUE THREAD

**Issue by deepakraous** [o1-labs/snarky#34]
Trying to run the following as per [specification](https://github.com/o1-labs/snarky):
**dune exec examples/tutorial/tutorial.exe**
<img width="1225" alt="screen shot 2018-09-15 at 2 39 14 pm" src="https://user-images.githubusercontent.com/3477488/45590779-9caecd80-b8f5-11e8-9542-4628f17c5bd5.png">

**Comment by jochasinga** [comment]
@deepakraous  The exception was intentionally raised here
https://github.com/o1-labs/snarky/blob/1844ba76d53f49473adcfedf9b15e2efeaf7bb7f/examples/tutorial/tutorial.ml#L224

You have to write the matrix mul operations and write snark proof for the sqrt.

**Comment by bkase** [comment]
Closing as the exception is intentional as @jochasinga said
