### ISSUE TITLE
Frobenius Test not passing for Fq4 in libsnark

### ISSUE THREAD

**Issue by DanieleDiBenedetto** [o1-labs/snarky#384]
Hi,
I tried to run: 

```
mnt4753_pp::init_public_params();
test_Frobenius<mnt4753_Fq4>();
```

But the test is not passing. I did a little bit of debug and discovered that the assertion:

`assert(a_qi == a_q)`

fails whenever: 
`
power % 4 = 3
`

i.e. there seems to be a problem with Frobenius Coefficient FP4 C1 [3]. 
Is this known or am I doing something wrong ? 
Thanks in advance

**Comment by paberr** [comment]
I stumbled across the exact same issue and would love to know the answer to this!
