### ISSUE TITLE
[Question] Can Snarky do recursive snarks?

### ISSUE THREAD

**Issue by brunoffranca** [o1-labs/snarky#397]
Can Snarky do the kind of recursive snarks that appear on the Coda paper? Is there any examples or documentation on that?

**Comment by mrmr1993** [comment]
Yes: there are implementations of both Groth-Maller and Bowe-Gabizon verifiers implemented in snarky [here](https://github.com/CodaProtocol/coda/tree/develop/src/lib/snarky_verifier) in the coda repo.

You can verify proofs as part of another SNARK using those implementations, but be aware that you will need to use pairing-friendly curves (e.g. the MNT curves) to get recursive SNARKs. The coda repo is the best place to see those in action at the moment.
