### ISSUE TITLE
[Question] Which exact MNT4 and MNT6 curves are supported?

### ISSUE THREAD

**Issue by brunoffranca** [o1-labs/snarky#460]
It seems that the MNT4 and MNT6 curves are supported by snarky. But it's not clear which exact curves. Are they the MNT curves with 298 bit fields used in the paper "Scalable Zero Knowledge via Cycles of Elliptic Curves" or the MNT curves with 753 bit fields being used in Coda (https://coinlist.co/build/coda/pages/theory#pairing-friendly-cycles-and-recursive-composition)?

**Comment by paberr** [comment]
As far as I can see [here](https://github.com/o1-labs/snarky/tree/master/src/camlsnark_c/libsnark-caml/depends/libff/libff/algebra/curves), it has support for both curves.
