### ISSUE TITLE
Building on Mac OS X

### ISSUE THREAD

**Issue by alerdenisov** [o1-labs/snarky#5]
I've a lot of trouble to build snarky on macosx, but solve it by myself.

I'm not ready to pull request (because of lack of compatibility with other platforms), but solution is:

> ISSUE: `libprocps` unavailable at macos x

**Solution:** Change line 26 in [./src/camlsnark_c/jbuild](https://github.com/o1-labs/snarky/blob/master/src/camlsnark_c/jbuild) with:
```
    cmake -DUSE_PT_COMPRESSION=OFF -DWITH_PROCPS=OFF -DWITH_SUPERCOP=OFF ..
```

> ISSUE: no member named `emplace_back` in `std::vector<bool>` until C++14

**Solution:** Change C++ std version on C++14 at line 108 in [./src/camlsnark_c/libsnark-caml/CMakeList.txt]():
```
    "${CMAKE_CXX_FLAGS} -std=c++14 -Wall -Wextra -Wfatal-errors"
```

**Comment by alerdenisov** [comment]
But I still have a trouble with ppx_deriving. And have no idea how to solve it:
```
# [...]
# File "src/snark_intf.ml", line 415, characters 42-46:
# Error: ppx_type_conv: 'enum' is not a supported signature type type-conv generator
#          ppx src/enumerable.pp.ml (exit 1)
# (cd _build/default && ./.ppx/ppx_deriving.enum+ppx_jane+ppx_driver.runner/ppx.exe --dump-ast --cookie 'library-name="snarky"' -diff-cmd - -o src/enumerable.pp.ml --impl src/enumerable.ml)
# File "src/enumerable.ml", line 12, characters 66-70:
# Error: ppx_type_conv: 'enum' is not a supported signature type type-conv generator
#          ppx src/enumerable.pp.mli (exit 1)
# (cd _build/default && ./.ppx/ppx_deriving.enum+ppx_jane+ppx_driver.runner/ppx.exe --dump-ast --cookie 'library-name="snarky"' -diff-cmd - -o src/enumerable.pp.mli --intf src/enumerable.mli)
# File "src/enumerable.mli", line 2, characters 66-70:
# Error: ppx_type_conv: 'enum' is not a supported signature type type-conv generator
```

**Comment by cmr** [comment]
I've got about 85% of the way to a working build on macOS. There's some linker incompatibility issues that means we need a dune feature to have the build work on both Linux and macOS without taking control of the compilation process for camlsnark_c (need to specify different `c_library_flags`). I'll also need to upstream some changes to orocksdb.

**Comment by bkase** [comment]
This works now! Let us know if anyone is still having trouble.
