### ISSUE TITLE
calling circuit functions (that can act on a global) outside of any circuit

### ISSUE THREAD

**Issue by fabrizio-m** [o1-labs/snarky#722]
To call a circuit function, you need to call it from Snark.constraint_system or Snark.generate_witness (because it init the global state).
The test should cover function calls directly without going through the APIs.

**Comment by o1-david** [comment]
to call a circuit function, you need to call it from Snark.constraint_system or Snark.generate_witness (because it init the global state), but what if you call the function directly without going through the APIs?

**Comment by fabrizio-m** [comment]
Replaced by #778
