### ISSUE TITLE
test: calling circuit functions inside a circuit inside a prover block inside another circuit

### ISSUE THREAD

**Issue by fabrizio-m** [o1-labs/snarky#726]

**Comment by o1-david** [comment]
what we had in mind: a generate_witness run on a circuit that at some point creates a proof (or we can generate a witness instead if we want to avoid proof) and includes it as a witness

**Comment by o1-david** [comment]
(as in, we have a stack of global state that we push and pop)

(token zkapp test does that (depth-3 recursion))

**Comment by joseandro** [comment]
Replaced by #778
