### ISSUE TITLE
create a test to serialize protocol circuits as well

### ISSUE THREAD

**Issue by o1-david** [o1-labs/snarky#777]

**Comment by o1-david** [comment]
@mrmr1993 add pointers to the circuits here?

**Comment by mrmr1993** [comment]
Blockchain snark rules: https://github.com/MinaProtocol/mina/blob/8765422cf251dfa4e36a0dcdab9f98dc03ed200a/src/lib/blockchain_snark/blockchain_snark_state.ml#L442
Transaction snark rules: https://github.com/MinaProtocol/mina/blob/8765422cf251dfa4e36a0dcdab9f98dc03ed200a/src/lib/transaction_snark/transaction_snark.ml#L3468

Probably best to expose the circuits that pickles generates by adding a helper to the values returned by `Pickles.compile`
