### ISSUE TITLE
Dockerfile is broken

### ISSUE THREAD

**Issue by udibr** [o1-labs/snarky#91]
I'm trying to build a docker image. clearly the line
https://github.com/o1-labs/snarky/blob/master/Dockerfile#L56
```
RUN eval "$opam config env)" && \
```
needs to be fixed to 
```
RUN eval "$(opam config env)" && \
```
I had to make other modifications:
such as
```
-ARG OCAML_VERSION=4.07.1
+ARG OCAML_VERSION=4.07.0
-    apt-get --no-install-recommends -q -y install \
+    apt-get --no-install-recommends -q -y install rsync \
+RUN echo "check_certificate = off" >> ~/.wgetrc
```
but even then I got an error from 'opam pin add -y interval_union .'
that 
```
# Error: Version 1.6 of dune is not supported.
```
however if I run the partial docker image I can see that dune version is 1.2.1 and that the command 'opam pin add -y interval_union .' executes manually.
However I couldn't find how to manually make 'opam pin add -y bitstring_lib .' and 'opam pin add -y snarky .' work. In both cases I get the message
```
Sorry, no solution found: there seems to be a problem with your request.
```

please help

**Comment by udibr** [comment]
also [here](https://github.com/o1-labs/snarky/blob/master/dune-project#L1) it says that dune 1.6 should be used which comes with opam 2 while [here](https://github.com/o1-labs/snarky/blob/master/Dockerfile#L25) it say that opam 1.2.2 should be used

**Comment by mrmr1993** [comment]
@udibr I've put together PR #93 with a new dockerfile, can you try it out and see if it fixes the issues you were seeing?

**Comment by udibr** [comment]
its working! thanks
