### ISSUE TITLE
where can I fund the resulting compiled R1CS or snarks?

### ISSUE THREAD

**Issue by udibr** [o1-labs/snarky#94]
I tried running `dune exec --root=. ./examples/election/election_main.exe` which gave a printout which looks like an R1CS file was generated.
```
...
* Proof size in bits: 1019
```
but where can I find the proof itself?

**Comment by imeckler** [comment]
Hi @udibr -- the program is generating a proof internally, so the proof is in the memory of the program but doesn't get printed out. Are you looking for a function to print out the proof perhaps?

**Comment by udibr** [comment]
Ideally I would like to see CLI like[ZoKrates](https://zokrates.github.io/) or [snarkjs](https://github.com/iden3/snarkjs)

**Comment by imeckler** [comment]
Great suggestion -- we'll try to get to this soon.
